# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ume.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'ume.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import events_pb2 as events__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tume.proto\x12\x03ume\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x0c\x65vents.proto\"\x1d\n\x0b\x43ypherQuery\x12\x0e\n\x06\x63ypher\x18\x01 \x01(\t\"8\n\x0c\x43ypherResult\x12(\n\x07records\x18\x01 \x03(\x0b\x32\x17.google.protobuf.Struct\"7\n\x0c\x43ypherRecord\x12\'\n\x06record\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct\"0\n\x13VectorSearchRequest\x12\x0e\n\x06vector\x18\x01 \x03(\x02\x12\t\n\x01k\x18\x02 \x01(\x05\"#\n\x14VectorSearchResponse\x12\x0b\n\x03ids\x18\x01 \x03(\t\"\x1d\n\x0c\x41uditRequest\x12\r\n\x05limit\x18\x01 \x01(\x05\"S\n\nAuditEntry\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0e\n\x06reason\x18\x03 \x01(\t\x12\x11\n\tsignature\x18\x04 \x01(\t\"1\n\rAuditResponse\x12 \n\x07\x65ntries\x18\x01 \x03(\x0b\x32\x0f.ume.AuditEntry\";\n\x13PublishEventRequest\x12$\n\x08\x65nvelope\x18\x01 \x01(\x0b\x32\x12.ume.EventEnvelope\"#\n\x04Task\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07payload\x18\x02 \x01(\t\">\n\nTaskResult\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x0f\n\x07task_id\x18\x02 \x01(\t\x12\r\n\x05score\x18\x03 \x01(\x01\" \n\x0bPlanRequest\x12\x11\n\tobjective\x18\x01 \x01(\t\"(\n\x0cPlanResponse\x12\x18\n\x05tasks\x18\x01 \x03(\x0b\x32\t.ume.Task2\xb0\x02\n\x03UME\x12\x30\n\tRunCypher\x12\x10.ume.CypherQuery\x1a\x11.ume.CypherResult\x12\x35\n\x0cStreamCypher\x12\x10.ume.CypherQuery\x1a\x11.ume.CypherRecord0\x01\x12\x44\n\rSearchVectors\x12\x18.ume.VectorSearchRequest\x1a\x19.ume.VectorSearchResponse\x12\x38\n\x0fGetAuditEntries\x12\x11.ume.AuditRequest\x1a\x12.ume.AuditResponse\x12@\n\x0cPublishEvent\x12\x18.ume.PublishEventRequest\x1a\x16.google.protobuf.Empty2k\n\x11\x41gentOrchestrator\x12+\n\x04Plan\x12\x10.ume.PlanRequest\x1a\x11.ume.PlanResponse\x12)\n\x0b\x45xecuteTask\x12\t.ume.Task\x1a\x0f.ume.TaskResultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ume_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CYPHERQUERY']._serialized_start=91
  _globals['_CYPHERQUERY']._serialized_end=120
  _globals['_CYPHERRESULT']._serialized_start=122
  _globals['_CYPHERRESULT']._serialized_end=178
  _globals['_CYPHERRECORD']._serialized_start=180
  _globals['_CYPHERRECORD']._serialized_end=235
  _globals['_VECTORSEARCHREQUEST']._serialized_start=237
  _globals['_VECTORSEARCHREQUEST']._serialized_end=285
  _globals['_VECTORSEARCHRESPONSE']._serialized_start=287
  _globals['_VECTORSEARCHRESPONSE']._serialized_end=322
  _globals['_AUDITREQUEST']._serialized_start=324
  _globals['_AUDITREQUEST']._serialized_end=353
  _globals['_AUDITENTRY']._serialized_start=355
  _globals['_AUDITENTRY']._serialized_end=438
  _globals['_AUDITRESPONSE']._serialized_start=440
  _globals['_AUDITRESPONSE']._serialized_end=489
  _globals['_PUBLISHEVENTREQUEST']._serialized_start=491
  _globals['_PUBLISHEVENTREQUEST']._serialized_end=550
  _globals['_TASK']._serialized_start=552
  _globals['_TASK']._serialized_end=587
  _globals['_TASKRESULT']._serialized_start=589
  _globals['_TASKRESULT']._serialized_end=651
  _globals['_PLANREQUEST']._serialized_start=653
  _globals['_PLANREQUEST']._serialized_end=685
  _globals['_PLANRESPONSE']._serialized_start=687
  _globals['_PLANRESPONSE']._serialized_end=727
  _globals['_UME']._serialized_start=730
  _globals['_UME']._serialized_end=1034
  _globals['_AGENTORCHESTRATOR']._serialized_start=1036
  _globals['_AGENTORCHESTRATOR']._serialized_end=1143
# @@protoc_insertion_point(module_scope)
