from scripts import check_generated_protos
from scripts import compile_protos


def test_generated_protobuf_guard_allows_only_canonical_directories(tmp_path, monkeypatch):
    approved_server = tmp_path / "src" / "ume" / "proto"
    approved_client = tmp_path / "src" / "ume_client"
    approved_server.mkdir(parents=True)
    approved_client.mkdir(parents=True)

    monkeypatch.setattr(check_generated_protos, "BASE_DIR", tmp_path)
    monkeypatch.setattr(
        check_generated_protos,
        "APPROVED_DIRS",
        {approved_server.resolve(), approved_client.resolve()},
    )

    (approved_server / "events_pb2.py").write_text(
        "# Generated by the protocol buffer compiler.  DO NOT EDIT!\n",
        encoding="utf-8",
    )
    (approved_client / "ume_pb2_grpc.py").write_text(
        "# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!\n",
        encoding="utf-8",
    )
    (tmp_path / "ume_pb2.py").write_text(
        "# Generated by the protocol buffer compiler.  DO NOT EDIT!\n",
        encoding="utf-8",
    )
    (tmp_path / "src" / "events_pb2.py").parent.mkdir(parents=True, exist_ok=True)
    (tmp_path / "src" / "events_pb2.py").write_text(
        "from ume.proto.events_pb2 import *\n",
        encoding="utf-8",
    )

    assert check_generated_protos.main() == 1


def test_generated_protobuf_guard_ignores_shims(tmp_path, monkeypatch):
    approved_server = tmp_path / "src" / "ume" / "proto"
    approved_client = tmp_path / "src" / "ume_client"
    approved_server.mkdir(parents=True)
    approved_client.mkdir(parents=True)

    monkeypatch.setattr(check_generated_protos, "BASE_DIR", tmp_path)
    monkeypatch.setattr(
        check_generated_protos,
        "APPROVED_DIRS",
        {approved_server.resolve(), approved_client.resolve()},
    )

    (tmp_path / "ume_pb2.py").write_text(
        "from ume_client.ume_pb2 import *\n",
        encoding="utf-8",
    )
    (tmp_path / "src" / "events_pb2.py").parent.mkdir(parents=True, exist_ok=True)
    (tmp_path / "src" / "events_pb2.py").write_text(
        "from ume.proto.events_pb2 import *\n",
        encoding="utf-8",
    )

    assert check_generated_protos.main() == 0


def test_compile_protos_requires_grpc_tools(monkeypatch, tmp_path):
    monkeypatch.setattr(compile_protos, "PROTO_DIR", tmp_path)
    monkeypatch.setattr(
        compile_protos.importlib.resources,
        "files",
        lambda package: (_ for _ in ()).throw(ModuleNotFoundError(package)),
    )

    proto_file = tmp_path / "ume.proto"
    proto_file.write_text('syntax = "proto3";\npackage ume;\n', encoding="utf-8")

    try:
        compile_protos._run_protoc(tmp_path / "server", tmp_path / "client", [proto_file])
    except RuntimeError as exc:
        assert "grpc_tools is required" in str(exc)
    else:
        raise AssertionError("expected grpc_tools requirement error")
