FROM python:3.12-slim
# Python 3.12 is needed for FastAPI's Pydantic 2 stack
WORKDIR /app
RUN pip install poetry
COPY pyproject.toml poetry.lock ./
RUN poetry install --no-root --no-dev
RUN poetry run python -m spacy download en_core_web_lg
COPY src/ /app/src
ENV PYTHONPATH=/app
CMD ["poetry", "run", "uvicorn", "ume.api:app", "--host", "0.0.0.0", "--port", "8000"]

