version: '3.8'
services:
  redpanda:
    image: redpandadata/redpanda:latest
    command:
      - redpanda
      - start
      - --smp 1
      - --overprovisioned
      - --node-id 0
      - --check=false
      - --kafka-addr PLAINTEXT://0.0.0.0:29092,OUTSIDE://localhost:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda:29092,OUTSIDE://localhost:9092
    volumes:
      - ./certs:/etc/redpanda/certs:ro
    ports:
      - "9092:9092"
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster health | grep -E 'Healthy:.+true' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  schema-registry:
    image: redpandadata/console:latest
    depends_on:
      redpanda:
        condition: service_healthy
    ports:
      - "8081:8080"
    environment:
      REDPANDA_ADMIN_HOSTS: "redpanda:9644"
      REDPANDA_BROKERS: "redpanda:29092"
      CONFIG_FILEPATH: /tmp/config.yaml

  privacy-agent:
    build:
      context: ..
      dockerfile: Dockerfile.privacy-agent
    depends_on:
      redpanda:
        condition: service_healthy
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "redpanda:29092"
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f privacy_agent.py || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  ume-api:
    build:
      context: ..
      dockerfile: Dockerfile.privacy-agent
    command: uvicorn ume.api:app --host 0.0.0.0 --port 8000
    depends_on:
      redpanda:
        condition: service_healthy
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "redpanda:29092"
      UME_DB_PATH: "/data/ume_graph.db"
    ports:
      - "8000:8000"
    volumes:
      - ume-db:/data
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f uvicorn || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  ume-db:
