# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events.proto
"""Generated protocol buffer code."""
# mypy: ignore-errors
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x65vents.proto\x12\x03ume\x1a\x1cgoogle/protobuf/struct.proto\"\xe7\x01\n\rEventEnvelope\x12\x16\n\x0eschema_version\x18\x01 \x01(\t\x12&\n\x0b\x63reate_node\x18\x02 \x01(\x0b\x32\x0f.ume.CreateNodeH\x00\x12;\n\x16update_node_attributes\x18\x03 \x01(\x0b\x32\x19.ume.UpdateNodeAttributesH\x00\x12&\n\x0b\x63reate_edge\x18\x04 \x01(\x0b\x32\x0f.ume.CreateEdgeH\x00\x12&\n\x0b\x64\x65lete_edge\x18\x05 \x01(\x0b\x32\x0f.ume.DeleteEdgeH\x00\x42\t\n\x07payload\"\xb6\x01\n\tBaseEvent\x12\x10\n\x08\x65vent_id\x18\x01 \x01(\t\x12\x12\n\nevent_type\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\x03\x12\x0e\n\x06source\x18\x04 \x01(\t\x12\x0f\n\x07node_id\x18\x05 \x01(\t\x12\x16\n\x0etarget_node_id\x18\x06 \x01(\t\x12\r\n\x05label\x18\x07 \x01(\t\x12(\n\x07payload\x18\x08 \x01(\x0b\x32\x17.google.protobuf.Struct\"*\n\nCreateNode\x12\x1c\n\x04meta\x18\x01 \x01(\x0b\x32\x0e.ume.BaseEvent\"4\n\x14UpdateNodeAttributes\x12\x1c\n\x04meta\x18\x01 \x01(\x0b\x32\x0e.ume.BaseEvent\"*\n\nCreateEdge\x12\x1c\n\x04meta\x18\x01 \x01(\x0b\x32\x0e.ume.BaseEvent\"*\n\nDeleteEdge\x12\x1c\n\x04meta\x18\x01 \x01(\x0b\x32\x0e.ume.BaseEventb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'events_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EVENTENVELOPE._serialized_start=52
  _EVENTENVELOPE._serialized_end=283
  _BASEEVENT._serialized_start=286
  _BASEEVENT._serialized_end=468
  _CREATENODE._serialized_start=470
  _CREATENODE._serialized_end=512
  _UPDATENODEATTRIBUTES._serialized_start=514
  _UPDATENODEATTRIBUTES._serialized_end=566
  _CREATEEDGE._serialized_start=568
  _CREATEEDGE._serialized_end=610
  _DELETEEDGE._serialized_start=612
  _DELETEEDGE._serialized_end=654
# @@protoc_insertion_point(module_scope)
