#!/usr/bin/env python
"""Fail when generated protobuf files exist outside approved canonical directories."""

from __future__ import annotations

import sys
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
APPROVED_DIRS = {
    (BASE_DIR / "src" / "ume" / "proto").resolve(),
    (BASE_DIR / "src" / "ume" / "protos").resolve(),
    (BASE_DIR / "src" / "ume_client").resolve(),
}
GENERATED_MARKERS = (
    "Generated by the protocol buffer compiler.  DO NOT EDIT!",
    "Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!",
)


def _is_generated_proto(path: Path) -> bool:
    if not path.is_file():
        return False
    try:
        text = path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return False
    return any(marker in text for marker in GENERATED_MARKERS)


def _is_approved(path: Path) -> bool:
    resolved = path.resolve()
    return any(resolved.parent == approved_dir for approved_dir in APPROVED_DIRS)


def main() -> int:
    offenders = []
    for path in BASE_DIR.rglob("*_pb2*.py"):
        if ".git" in path.parts:
            continue
        if _is_generated_proto(path) and not _is_approved(path):
            offenders.append(path.relative_to(BASE_DIR))

    if offenders:
        print("Generated protobuf files must live only in approved directories:", file=sys.stderr)
        for offender in sorted(offenders):
            print(f" - {offender}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
