name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  lint-and-install:
    runs-on: ubuntu-latest
    outputs:
      run: ${{ steps.changes.outputs.run }}
    steps:
      - uses: actions/checkout@v4
      - name: Decide whether to run CI
        id: changes
        run: |
          python scripts/ci_should_run.py
          status=$?
          if [ "$status" = 0 ]; then echo "run=true" >> "$GITHUB_OUTPUT"; else echo "run=false" >> "$GITHUB_OUTPUT"; fi
      - uses: ./.github/actions/setup-python-poetry
        with:
          python-version: '3.12'
          run: ${{ steps.changes.outputs.run }}

      - name: Run pre-commit
        if: steps.changes.outputs.run == 'true'
        run: poetry run pre-commit run --all-files --show-diff-on-failure --color always

      - name: Set up Node.js
        if: steps.changes.outputs.run == 'true'
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install frontend dependencies and build
        if: steps.changes.outputs.run == 'true'
        working-directory: frontend
        run: |
          npm ci
          npm run build

  unit-tests:
    runs-on: ubuntu-latest
    needs: lint-and-install
    if: needs.lint-and-install.outputs.run == 'true'
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-python-poetry
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run unit tests with coverage
        run: poetry run pytest --cov=ume --cov-report xml --cov-fail-under=30 -m "not integration"

  integration-tests:
    runs-on: ubuntu-latest
    needs: lint-and-install
    if: needs.lint-and-install.outputs.run == 'true'
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-python-poetry
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run integration tests
        env:
          UME_DOCKER_TESTS: true
        run: poetry run pytest -m integration

  compose-smoke:
    runs-on: ubuntu-latest
    needs: [unit-tests, integration-tests]
    steps:
      - uses: actions/checkout@v4
      - name: Start stack
        run: |
          cd docker
          docker compose up -d
      - name: Wait for Redpanda health
        run: |
          cd docker
          for i in {1..30}; do
            status=$(docker compose ps --format '{{.Name}} {{.Health}}' | grep redpanda | awk '{print $2}')
            if [ "$status" = "healthy" ]; then exit 0; fi
            sleep 5
          done
          docker compose logs redpanda
          exit 1
      - name: Wait for privacy-agent health
        run: |
          cd docker
          for i in {1..30}; do
            status=$(docker compose ps --format '{{.Name}} {{.Health}}' | grep privacy-agent | awk '{print $2}')
            if [ "$status" = "healthy" ]; then exit 0; fi
            sleep 5
          done
          docker compose logs privacy-agent
          exit 1
      - name: Check privacy-agent running
        run: |
          cd docker
          docker compose ps privacy-agent
      - name: Tear down
        if: always()
        run: |
          cd docker
          docker compose down -v
