name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v4
      - name: Decide whether to run CI
        id: changes
        run: |
          python scripts/ci_should_run.py
          status=$?
          if [ "$status" = 0 ]; then echo "run=true" >> "$GITHUB_OUTPUT"; else echo "run=false" >> "$GITHUB_OUTPUT"; fi
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        if: steps.changes.outputs.run == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-interaction --no-ansi --with dev
      - name: Run pre-commit
        if: steps.changes.outputs.run == 'true'
        run: poetry run pre-commit run --all-files --show-diff-on-failure --color always
      - name: Run tests with coverage
        if: steps.changes.outputs.run == 'true'
        env:
          UME_DOCKER_TESTS: true
        run: poetry run pytest --cov=ume --cov-report xml --cov-fail-under=80
