name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - name: Check out code
        uses: actions/checkout@v4 # Updated to v4

      - name: Set up Python
        uses: actions/setup-python@v5 # Updated to v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry

      - name: Configure Poetry
        run: |
          poetry config virtualenvs.create false --local
          # Disables creation of a new virtual environment by Poetry within the project directory for CI
          # --local flag makes this configuration specific to the current project

      - name: Install dependencies
        run: |
          poetry install --no-interaction --no-ansi --with dev
          # --with dev ensures dev dependencies like pytest and ruff are installed

      - name: Run unit tests (pytest)
        run: |
          poetry run pytest --maxfail=1 --disable-warnings -q tests/

      - name: Check coverage (pytest-cov)
        run: |
          poetry run pytest --cov=src/ume --cov-report=xml --cov-report=term-missing tests/
          # Generates term-missing report for console and xml for potential external tools

      - name: Lint with Ruff
        run: |
          poetry run ruff check src tests

      - name: Check formatting with Ruff
        run: |
          poetry run ruff format --check src tests
