name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install . pytest pytest-cov pre-commit
      - name: Lint and Test
        run: |
          pre-commit run --files tests/test_client_module.py tests/test_privacy_agent_additional.py
          pytest tests/test_client_module.py tests/test_privacy_agent_additional.py --cov=ume.client --cov=ume.privacy_agent --cov-report xml --cov-fail-under=50
