# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# ruff: noqa
# mypy: ignore-errors
# source: graph_v2.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0egraph_v2.proto\x12\x0cume.graph.v2\"\x8b\x01\n\x04Node\x12\n\n\x02id\x18\x01 \x01(\t\x12\x36\n\nattributes\x18\x02 \x03(\x0b\x32\".ume.graph.v2.Node.AttributesEntry\x12\x0c\n\x04type\x18\x03 \x01(\t\x1a\x31\n\x0f\x41ttributesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"5\n\x04\x45\x64ge\x12\x0e\n\x06source\x18\x01 \x01(\t\x12\x0e\n\x06target\x18\x02 \x01(\t\x12\r\n\x05label\x18\x03 \x01(\t\"M\n\x05Graph\x12!\n\x05nodes\x18\x01 \x03(\x0b\x32\x12.ume.graph.v2.Node\x12!\n\x05\x65\x64ges\x18\x02 \x03(\x0b\x32\x12.ume.graph.v2.Edgeb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'graph_v2_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NODE_ATTRIBUTESENTRY._options = None
  _NODE_ATTRIBUTESENTRY._serialized_options = b'8\001'
  _NODE._serialized_start=33
  _NODE._serialized_end=172
  _NODE_ATTRIBUTESENTRY._serialized_start=123
  _NODE_ATTRIBUTESENTRY._serialized_end=172
  _EDGE._serialized_start=174
  _EDGE._serialized_end=227
  _GRAPH._serialized_start=229
  _GRAPH._serialized_end=306
# @@protoc_insertion_point(module_scope)
